version: '3'
services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - testapp
  testapp:
    restart: always
    build: ./node_test
    ports:
      - '5000:5000'
